### ISSUE TITLE
npm ERROR

### ISSUE THREAD

**Issue by ibnahmadbello** [BolajiOlajide/UserManager#7]
Greetings.
I observed an npm ERROR whenever I run 'npm test' in my machine. Though, I have successfully debug and pass the test. I felt I should inform you because it is a typo stuff, not from my side but from the autogenerated folder

**Comment by Ileriayo** [comment]
The [README.md](https://github.com/BolajiOlajide/UserManager#testing) has it that `npm test` is not functional right now.

**Comment by ibnahmadbello** [comment]
Well, the issue is that when you run the `npm test` it tries to look for a `test` folder in the directory whereas the folder created was `tests`. I had to resolve by renaming the folder to `test`.

**Comment by ibnahmadbello** [comment]
Maybe, I should close the issue because it is just an observation.

**Comment by ibnahmadbello** [comment]
The issue is that when you run the `npm test`. It looks for a `test` folder in the directory whereas the folder created is named `tests`. I resolve the issue by renaming the folder to `test`.

**Comment by BolajiOlajide** [comment]
Hello @ibnahmadbello @Ileriayo 
Thanks for pointing this out. Actually their is no test suite in the project right now, that's why I didn't add the package for testing (Jasmine). As soon as the assessment is complete, I'd write test for the server side and correct this.

For now, I'll make a change to ensure you don't get an npm error when you run `npm test`.
Thanks once again!

**Comment by ibnahmadbello** [comment]
No problem. Just my little observation. It was Jasmine stuff exactly.
